export const expansions = new Map<string, string>([
    // Scarlet & Violet Era
    ["SVI", "Scarlet Violet"],
    ["PAL", "Paldea Evolved"],
    ["OBF", "Obsidian Flames"],
    ["MEW", "151"],
    ["PAR", "Paradox Rift"],
    ["PAF", "Paldean Fates"],
    ["TEF", "Temporal Forces"],
    ["TWM", "Twilight Masquerade"],
    ["SFA", "Shrouded Fable"],
    ["SCR", "Stellar Crown"],
    ["SSP", "Surging Sparks"],
    ["PRE", "Prismatic Evolutions"],
    ["JTG", "Journey Together"],
    ["", "Destined Rivals"],
    ["", "Black Bolt"],
    ["", "White Flare"],
    // Sword & Shield Era
    ["SSH", "Sword Shield"],
    ["RCL", "Rebel Clash"],
    ["DAA", "Darkness Ablaze"],
    ["CPA", "Champion's Path"],
    ["VIV", "Vivid Voltage"],
    ["SHF", "Shining Fates"],
    ["BST", "Battle Styles"],
    ["CRE", "Chilling Reign"],
    ["EVS", "Evolving Skies"],
    ["CEL", "Celebrations"],
    ["FST", "Fusion Strike"],
    ["BRS", "Brilliant Stars"],
    ["ASR", "Astral Radiance"],
    ["PGO", "Pokemon GO"],
    ["LOR", "Lost Origin"],
    ["SIT", "Silver Tempest"],
    ["CRZ", "Crown Zenith"],
    // Sun & Moon Era
    ["SUM", "Sun Moon"],
    ["GRI", "Guardians Rising"],
    ["BUS", "Burning Shadows"],
    ["SLG", "Shining Legends"],
    ["CIN", "Crimson Invasion"],
    ["UPR", "Ultra Prism"],
    ["FLI", "Forbidden Light"],
    ["CES", "Celestial Storm"],
    ["DRM", "Dragon Majesty"],
    ["LOT", "Lost Thunder"],
    ["TEU", "Team Up"],
    ["DET", "Detective Pikachu"],
    ["UNB", "Unbroken Bonds"],
    ["UNM", "Unified Minds"],
    ["HIF", "Hidden Fates"],
    ["CEC", "Cosmic Eclipse"],
    // XY Era
    ["KSS", "Kalos Starter Set"],
    ["XY", "XY"],
    ["FLF", "Flashfire"],
    ["FFI", "Furious Fists"],
    ["PHF", "Phantom Forces"],
    ["PRC", "Primal Clash"],
    ["DCR", "Double Crisis"],
    ["ROS", "Roaring Skies"],
    ["AOR", "Ancient Origins"],
    ["BKT", "BREAKthrough"],
    ["BKP", "BREAKpoint"],
    ["GEN", "Generations"],
    ["FCO", "Fates Collide"],
    ["STS", "Steam Siege"],
    ["EVO", "Evolutions"],
    // Black & White Era
    ["BLW", "Black White"],
    ["EPO", "Emerging Powers"],
    ["NVI", "Noble Victories"],
    ["NXD", "Next Destinies"],
    ["DEX", "Dark Explorers"],
    ["DRX", "Dragons Exalted"],
    ["DRV", "Dragon Vault"],
    ["BCR", "Boundaries Crossed"],
    ["PLS", "Plasma Storm"],
    ["PLF", "Plasma Freeze"],
    ["PLB", "Plasma Blast"],
    ["LTR", "Legendary Treasures"],
    // HeartGold & SoulSilver Era
    ["HS", "HeartGold SoulSilver"],
    ["UL", "Unleashed"],
    ["UD", "Undaunted"],
    ["TM", "Triumphant"],
    ["CL", "Call of Legends"],
    // Platinum Era
    ["PL", "Platinum"],
    ["RR", "Rising Rivals"],
    ["SV", "Supreme Victors"],
    ["AR", "Arceus"],
    // Diamond & Pearl Era
    ["DP", "Diamond Pearl"],
    ["MT", "Mysterious Treasures"],
    ["SW", "Secret Wonders"],
    ["GE", "Great Encounters"],
    ["MD", "Majestic Dawn"],
    ["LA", "Legends Awakened"],
    ["STF", "Stormfront"],
    // EX Era
    ["RS", "EX Ruby Sapphire"],
    ["SS", "EX Sandstorm"],
    ["DR", "EX Dragon"],
    ["MA", "EX Team Magma vs Team Aqua"],
    ["HL", "EX Hidden Legends"],
    ["FL", "EX FireRed LeafGreen"],
    ["TRR", "EX Team Rocket Returns"],
    ["DX", "EX Deoxys"],
    ["EM", "EX Emerald"],
    ["UF", "EX Unseen Forces"],
    ["DS", "EX Delta Species"],
    ["LM", "EX Legend Maker"],
    ["HP", "EX Holon Phantoms"],
    ["CG", "EX Crystal Guardians"],
    ["DF", "EX Dragon Frontiers"],
    ["PK", "EX Power Keepers"],
    // e-Card Era
    ["EX", "Expedition Base Set"],
    ["AQ", "Aquapolis"],
    ["SK", "Skyridge"],
    // Neo Era
    ["NG", "Neo Genesis"],
    ["NDI", "Neo Discovery"],
    ["SI", "Southern Islands"],
    ["NR", "Neo Revelation"],
    ["NDE", "Neo Destiny"],
    ["LC", "Legendary Collection"],
    // Gym Era
    ["GH", "Gym Heroes"],
    ["GC", "Gym Challenge"],
    // Base Set Era
    ["BS", "Base Set"],
    ["JU", "Jungle"],
    ["FO", "Fossil"],
    ["B2", "Base Set 2"],
    ["TR", "Team Rocket"],
    ])